### ISSUE TITLE
Status 201

### ISSUE THREAD

**Issue by lionhard83** [parisimattia/restaurant-administrator#1]
https://github.com/parisimattia/restaurant-administrator/blob/064e341459775b420e13628c34d0dacbc6ef2bcd/routes/client.js#L15

**Comment by parisimattia** [comment]
Cos'è questo prof? Non ho capito bene

**Comment by parisimattia** [comment]
Cioè che tipo di errore ho fatto?

**Comment by parisimattia** [comment]
Ah si il codice errore è sbagliato  l'ho notato ora, errore di distrazione

**Comment by parisimattia** [comment]
risolto
