### ISSUE TITLE
getOrderIndex

### ISSUE THREAD

**Issue by lionhard83** [parisimattia/restaurant-administrator#2]
https://github.com/parisimattia/restaurant-administrator/blob/064e341459775b420e13628c34d0dacbc6ef2bcd/routes/admin.js#L31

Chiami la funzione `getOrderIndex` più di una volta, sarebbe stato meglio chiamarla una sola volta e salvare il risultato in una variabile temporanea, e verificare le condizioni sulla variabile temporanea.

**Comment by lionhard83** [comment]
`var index = orders.getOrderIndex(req.params.code);
if(Number.isInteger(parseInt(req.params.code)) && req.params.code >= 0
      && index != null
      && index != "error"
      &&  (req.query.status == 'ready'|| req.query.status == 'closed'`

**Comment by parisimattia** [comment]
Risolto
